# Generated by Django 3.0.2 on 2020-02-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_id',
            new_name='id',
        ),
    ]
